#!/usr/bin/env bash
# Memlayer cloud-hosted setup — deploy to Supabase (DB) + Fly.io (compute)
# Safe to re-run: saves state to ~/.config/memlayer/cloud.env
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/scripts/lib.sh"

TOTAL_STEPS=7
STATE_FILE="$HOME/.config/memlayer/cloud.env"
cd "$SCRIPT_DIR"

# ── Load previous state if available ─────────────────────────────
_load_state() {
    if [[ -f "$STATE_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$STATE_FILE"
        return 0
    fi
    return 1
}

_save_state() {
    mkdir -p "$(dirname "$STATE_FILE")"
    cat > "$STATE_FILE" <<STATEEOF
# Memlayer cloud config — generated by setup_cloud_hosted.sh
MEMLAYER_AUTH_TOKEN=${auth_token:-}
DATABASE_URL=${db_url:-}
OPENAI_API_KEY=${openai_key:-}
EMBEDDING_PROVIDER=${embedding_provider:-openai}
MEMLAYER_APP_NAME=${app_name:-memlayer}
MEMLAYER_REGION=${region:-iad}
STATEEOF
    chmod 600 "$STATE_FILE"
}

echo
echo "  Memlayer Cloud Setup"
echo "  ====================="
echo "  Deploy to Supabase (database) + Fly.io (server)"
echo

if _load_state; then
    info "Found previous config at $STATE_FILE"
    # Import saved values as defaults
    _prev_token="${MEMLAYER_AUTH_TOKEN:-}"
    _prev_db="${DATABASE_URL:-}"
    _prev_openai="${OPENAI_API_KEY:-}"
    _prev_app="${MEMLAYER_APP_NAME:-memlayer}"
    _prev_region="${MEMLAYER_REGION:-iad}"
    _prev_embed="${EMBEDDING_PROVIDER:-openai}"
else
    _prev_token="" _prev_db="" _prev_openai=""
    _prev_app="memlayer" _prev_region="iad" _prev_embed="openai"
fi

# ── Step 1: Prerequisites ───────────────────────────────────────────
step 1 $TOTAL_STEPS "Checking prerequisites"

require_cmd curl

if ! command -v flyctl &>/dev/null; then
    error "flyctl CLI is not installed"
    echo
    echo "  Install flyctl:"
    echo "    curl -L https://fly.io/install.sh | sh"
    echo
    echo "  Then authenticate:"
    echo "    flyctl auth login"
    exit 1
fi

# Verify flyctl is authenticated
if ! flyctl auth whoami &>/dev/null 2>&1; then
    error "flyctl is not authenticated"
    echo "  Run: flyctl auth login"
    exit 1
fi

success "flyctl CLI detected and authenticated"

# Billing warning
echo
warn "Fly.io requires billing info before deploying machines (even on the free tier)."
echo "  Set up billing at: https://fly.io/dashboard → Billing"
echo "  If you haven't done this, the deploy step will fail."
echo
if ! confirm "Have you added billing info to your Fly.io account?" "y"; then
    info "Add billing info first, then re-run this script."
    echo "  https://fly.io/dashboard"
    exit 0
fi

# ── Step 2: Supabase project ────────────────────────────────────────
step 2 $TOTAL_STEPS "Configuring Supabase database"

db_url=""

# Offer to reuse previous connection string
if [[ -n "$_prev_db" ]]; then
    info "Previous connection string found: $(mask_token "$_prev_db")"
    if confirm "Keep this connection string?" "y"; then
        db_url="$_prev_db"
    fi
fi

if [[ -z "$db_url" ]]; then
    echo
    info "You need a Supabase project with these extensions enabled:"
    echo "    - vector (pgvector)"
    echo "    - pg_trgm"
    echo
    info "To create one:"
    echo "    1. Go to https://supabase.com/dashboard"
    echo "    2. Create a new project (free tier is fine to start)"
    echo "    3. Go to Database → Extensions"
    echo "    4. Enable 'vector' and 'pg_trgm'"
    echo "    5. Go to Settings → Database → Connection string → URI"
    echo "       Use the DIRECT connection (port 5432), NOT the pooled connection (port 6543)"
    echo

    while true; do
        db_url=$(prompt_value "Paste your Supabase direct connection string" "")
        if [[ -z "$db_url" ]]; then
            error "Connection string cannot be empty"
            continue
        fi

        # Basic format validation
        if [[ ! "$db_url" =~ ^postgresql:// ]]; then
            warn "Connection string should start with postgresql://"
            if ! confirm "Continue anyway?" "n"; then
                continue
            fi
        fi

        # Warn about pooled connections
        if [[ "$db_url" =~ :6543 ]]; then
            warn "Port 6543 is the pooled connection (PgBouncer)."
            echo "  Memlayer uses asyncpg with prepared statements, which requires"
            echo "  the DIRECT connection on port 5432."
            if ! confirm "Continue with this URL anyway? (may cause errors)" "n"; then
                continue
            fi
        fi

        # Test connection
        printf "  Testing database connection... "
        if [[ "$db_url" =~ ^postgresql://[^:]+:[^@]+@[^/]+/[^?]+ ]]; then
            success "URL format looks valid"
        else
            warn "Could not validate URL format"
        fi

        break
    done
fi

success "Database configured"

# ── Step 3: Auth token ──────────────────────────────────────────────
step 3 $TOTAL_STEPS "Configuring auth token"

auth_token=""

# Reuse previous token if available (critical for idempotency)
if [[ -n "$_prev_token" ]]; then
    info "Existing auth token found: $(mask_token "$_prev_token")"
    if confirm "Keep this token? (recommended if re-running after a failure)" "y"; then
        auth_token="$_prev_token"
    fi
fi

if [[ -z "$auth_token" ]]; then
    auth_token=$(generate_secret)
    info "Generated new auth token: $(mask_token "$auth_token")"

    if ! confirm "Use this token?" "y"; then
        auth_token=$(prompt_value "Enter your auth token" "$auth_token")
    fi
fi

success "Auth token configured"

# ── Step 4: OpenAI embeddings ───────────────────────────────────────
step 4 $TOTAL_STEPS "Configuring embeddings"

openai_key=""
embedding_provider="$_prev_embed"

# Reuse previous key if available
if [[ -n "$_prev_openai" ]]; then
    info "Existing OpenAI key found: $(mask_token "$_prev_openai")"
    if confirm "Keep this key?" "y"; then
        openai_key="$_prev_openai"
    fi
fi

if [[ -z "$openai_key" ]]; then
    embedding_provider="openai"
    if confirm "Configure OpenAI embeddings? (recommended)" "y"; then
        while true; do
            openai_key=$(prompt_secret "OpenAI API key")
            if [[ -z "$openai_key" ]]; then
                warn "No key entered, skipping OpenAI embeddings"
                break
            fi
            printf "  Testing API key... "
            if test_openai_key "$openai_key"; then
                success "API key is valid"
                break
            else
                warn "API key test failed (invalid key or network error)"
                if ! confirm "Try a different key?" "y"; then
                    if confirm "Continue without OpenAI embeddings?" "y"; then
                        openai_key=""
                        info "Falling back to FTS-only mode"
                    fi
                    break
                fi
            fi
        done
    else
        info "Skipping OpenAI embeddings (FTS-only mode)"
    fi
fi

# ── Step 5: Fly.io app configuration ───────────────────────────────
step 5 $TOTAL_STEPS "Configuring Fly.io deployment"

app_name=$(prompt_value "Fly.io app name" "$_prev_app")

# Check if app already exists
if flyctl apps list --json 2>/dev/null | grep -q "\"$app_name\""; then
    info "Fly app '$app_name' already exists — will redeploy"
else
    info "Will create new Fly app: $app_name"
fi

# Select region
echo
info "Common Fly.io regions:"
echo "    iad  — Ashburn, Virginia (US East)"
echo "    ord  — Chicago (US Central)"
echo "    sjc  — San Jose (US West)"
echo "    lhr  — London"
echo "    ams  — Amsterdam"
echo "    nrt  — Tokyo"
echo "    syd  — Sydney"
region=$(prompt_value "Region" "$_prev_region")

# Update fly.toml
sed -i "s/^app = .*/app = \"$app_name\"/" fly.toml
sed -i "s/^primary_region = .*/primary_region = \"$region\"/" fly.toml

success "Fly.io config: app=$app_name, region=$region"

# ── Save state before deploy (so re-runs reuse same config) ───────
_save_state
info "Config saved to $STATE_FILE (will be reused if you re-run)"

# ── Step 6: Deploy ──────────────────────────────────────────────────
step 6 $TOTAL_STEPS "Deploying to Fly.io"

export DATABASE_URL="$db_url"
export MEMLAYER_AUTH_TOKEN="$auth_token"
export EMBEDDING_PROVIDER="$embedding_provider"
if [[ -n "$openai_key" ]]; then
    export OPENAI_API_KEY="$openai_key"
fi

if bash "$SCRIPT_DIR/deploy/fly-deploy.sh" "$app_name"; then
    success "Deployment complete"
else
    echo
    error "Deployment failed."
    echo
    echo "  Common causes:"
    echo "    - Billing info not set up → https://fly.io/dashboard → Billing"
    echo "    - Docker build error → check the output above"
    echo
    echo "  To retry (your config is saved, same token will be reused):"
    echo "    ./setup_cloud_hosted.sh"
    echo
    echo "  Or deploy directly:"
    echo "    source $STATE_FILE"
    echo "    ./deploy/fly-deploy.sh $app_name"
    exit 1
fi

# ── Step 7: Health check & summary ──────────────────────────────────
step 7 $TOTAL_STEPS "Verifying deployment"

server_url="https://$app_name.fly.dev"

if wait_for_url "$server_url/health" 90; then
    success "Server is healthy!"
else
    warn "Server did not become healthy within 90 seconds"
    echo
    echo "  Troubleshooting:"
    echo "    flyctl logs -a $app_name"
    echo
    echo "  Common causes:"
    echo "    - Database connection string may be wrong"
    echo "    - Extensions (vector, pg_trgm) may not be enabled in Supabase"
    echo "    - Supabase project may be paused (free tier pauses after 1 week)"
    echo
    echo "  To retry with a new connection string:"
    echo "    ./setup_cloud_hosted.sh"
    echo "    (select 'no' when asked to keep the existing connection string)"
fi

# Determine embedding status
embed_status="FTS-only (no OpenAI key)"
if [[ -n "$openai_key" ]]; then
    embed_status="OpenAI (text-embedding-3-small)"
fi

api_url="$server_url/api"

echo
print_box \
    "Memlayer Cloud — Deployed" \
    "" \
    "Server:      $server_url" \
    "API base:    $api_url" \
    "Embeddings:  $embed_status" \
    "" \
    "Auth Token:  $(mask_token "$auth_token")" \
    "Full token:  $auth_token"

echo
info "Config saved to $STATE_FILE"
info "Re-run this script at any time to update your deployment."
echo
info "To install the client on each machine where you use Claude Code:"
echo
echo "  Step 1 — download memlayer:"
echo "    curl -fsSL https://raw.githubusercontent.com/mikeydotio/memlayer/main/install.sh | bash"
echo
echo "  Step 2 — connect to your server:"
echo "    ~/.memlayer/setup_client.sh --server-url $api_url --auth-token $auth_token"
echo
info "To view logs:   flyctl logs -a $app_name"
info "To redeploy:    ./deploy/fly-deploy.sh $app_name"
info "To destroy:     flyctl apps destroy $app_name"
echo
