#!/usr/bin/env bash
# sync-version.sh — Synchronize version across all memlayer components
# Source of truth: VERSION file in repo root
set -euo pipefail

REPO_ROOT="${PROJECT_DIR:-$(git rev-parse --show-toplevel)}"
VERSION_FILE="$REPO_ROOT/VERSION"

if [ $# -ge 1 ]; then
    VERSION="$1"
else
    VERSION=$(cat "$VERSION_FILE" | tr -d 'v \n\r')
fi

if [ -z "$VERSION" ]; then
    echo "ERROR: No version found in $VERSION_FILE and none provided as argument" >&2
    exit 1
fi

echo "Syncing version: $VERSION"

# Rust Cargo.toml files — update the package version line
for cargo_file in \
    "$REPO_ROOT/daemon/Cargo.toml" \
    "$REPO_ROOT/cli-rs/Cargo.toml" \
    "$REPO_ROOT/memlayer-common/Cargo.toml"; do
    if [ -f "$cargo_file" ]; then
        sed -i "s/^version = \".*\"/version = \"$VERSION\"/" "$cargo_file"
        echo "  Updated $cargo_file"
    fi
done

# Python server pyproject.toml
PYPROJECT="$REPO_ROOT/server/pyproject.toml"
if [ -f "$PYPROJECT" ]; then
    sed -i "s/^version = \".*\"/version = \"$VERSION\"/" "$PYPROJECT"
    echo "  Updated $PYPROJECT"
fi

# Server _version.py (generated, used at runtime)
VERSION_PY="$REPO_ROOT/server/src/_version.py"
cat > "$VERSION_PY" <<EOF
# Auto-generated by scripts/sync-version.sh — do not edit manually
__version__ = "$VERSION"
EOF
echo "  Generated $VERSION_PY"

# Plugin manifest
PLUGIN_JSON="$REPO_ROOT/plugin/.claude-plugin/plugin.json"
if [ -f "$PLUGIN_JSON" ]; then
    # Use python for reliable JSON manipulation
    python3 -c "
import json, sys
with open('$PLUGIN_JSON') as f:
    data = json.load(f)
data['version'] = '$VERSION'
with open('$PLUGIN_JSON', 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
"
    echo "  Updated $PLUGIN_JSON"
fi

# Marketplace manifest — sync plugin version in plugins array
MARKETPLACE_JSON="$REPO_ROOT/.claude-plugin/marketplace.json"
if [ -f "$MARKETPLACE_JSON" ]; then
    python3 -c "
import json
with open('$MARKETPLACE_JSON') as f:
    data = json.load(f)
for p in data.get('plugins', []):
    if p.get('name') == 'memlayer':
        p['version'] = '$VERSION'
with open('$MARKETPLACE_JSON', 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
"
    echo "  Updated $MARKETPLACE_JSON"
fi

# Skill frontmatter versions
for SKILL_MD in "$REPO_ROOT"/plugin/skills/*/SKILL.md; do
    if [ -f "$SKILL_MD" ]; then
        sed -i "s/^version: .*/version: $VERSION/" "$SKILL_MD"
        echo "  Updated $SKILL_MD"
    fi
done

echo "Version sync complete: $VERSION"
